fix: Resize handler now resizes (#555)
* Resize handler now resizes - fix for #554

* Fix failing tests due to outdated chromedriver.
Fixes:
```
  1) Basic Tests chrome-local
       Displays skip ad button chrome-local:
     WebDriverError: unknown error: call function result missing 'value'

  2) Basic Tests chrome-local
       Nonlinear chrome-local:
     WebDriverError: unknown error: call function result missing 'value'
```